"""Fix many-to-many relationships

Revision ID: 47a115e9fa5d
Revises: 28f5cd1af054
Create Date: 2025-08-06 02:39:07.643341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a115e9fa5d'
down_revision: Union[str, Sequence[str], None] = '28f5cd1af054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cafes', type_='foreignkey')
    op.drop_column('cafes', 'owner_id')
    op.alter_column('reviews', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('cafes', sa.Column('owner_id', sa.NUMERIC(), nullable=False))
    op.create_foreign_key(None, 'cafes', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
